### PR TITLE
Update dev

### PR DESCRIPTION
**Pull request by Vinayakj009**
This update will allow the users to send commands to the arduino, while also allowing them to send loggable data to the cloud.

### CODE REVIEW

**Comment by rsbuilds** [comment]
@Vinayakj009  I think we can structure in the more structured way. 
For example : 
boltiot-arduino-helper 
src
 All your code go inside src folder
example
Put some .ino file with example
the readme file
licance

**Comment by rsbuilds** [comment]
@Vinayakj009  Also write the function description, function arguments and return type of each of functions.  It will make the code more readble.

**Comment by rsbuilds** [comment]
@Vinayakj009  Also if you can add some Fritzing digram about the Bolt to Ardunio connection then it will be great.

**Comment by rsbuilds** [comment]
@Vinayakj009  In readme code snippet, you can write the snippet by defining the language. 
```c++
    Bolt bolt();
```

**Comment by Vinayakj009** [comment]
@quelist : I had already done the structural changes. (Except for the licence file, will add that tomorrow).
Please look at the "update-dev" branch code, I have a feeling you are looking at the master branch.

**Comment by Vinayakj009** [comment]
@quelist : I will add the function arguments and description details, in the code. But do remember that in the long run, the users will never see this. Though putting it in the Readme would be a good idea (Which I was planning on doing from the start).

Code snippet in readme is something I did not know about. Will check how that works and implement it.

Fritzing diagram in readme is a great idea. Will definitely work on that.

**Pull request closed without merging**
